language: csharp
#mono: latest
mono: none
sudo: required
dist: xenial
dotnet: 2.2
env:
  global:
#    - FrameworkPathOverride="$(dirname $(which mono))/../lib/mono/4.5/"
    - NUGETURL=https://api.nuget.org/v3/index.json
    - VERSION=${TRAVIS_TAG:-0.0.0-dev}
    - MODE=Release
script:
  - echo $VERSION
  - dotnet restore ./
  - dotnet build ./ -c $MODE -p:Version=$VERSION -p:InformationalVersion=$VERSION:$TRAVIS_COMMIT
  - dotnet test ./ -c $MODE --no-build /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput='./TestResults/' 
script: |
    curl -Ls "https://github.com/codacy/csharp-codacy-coverage/releases/download/1.0.5/Codacy.CSharpCoverage_linux-x64" --output codacy
    chmod +x ./codacy
    coverfiles=$(find . -type f -name coverage.opencover.xml)
    for coverfile in $coverfiles; do
      ./codacy -c "$TRAVIS_COMMIT" -t "$CODACY_PROJECT_TOKEN" -r "$coverfile" -e opencover -p
    done
    if [ -n "$coverfiles" ]; then
      ./codacy -c "$TRAVIS_COMMIT" -t "$CODACY_PROJECT_TOKEN" -f
    fi
deploy:
  skip_cleanup: true
  provider: script
  script: dotnet pack ./ -c $MODE --no-build -p:Version=$VERSION && dotnet nuget push ./src/**/*.nupkg -s $NUGETURL -k $NUGETKEY
  on:
    tags: true
